# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10XDBZ_zxnVWze8o-Hc9VjZ7ojHKdS72P
"""

class Library:
    def __init__(self):
        self.file = open("books.txt", "a+")

    def __del__(self):
        self.file.close()

    def list_books(self):
        self.file.seek(0)
        books = self.file.read().splitlines()
        if books:
            for book in books:
                book_info = book.strip().split(',')
                print(f"Book: {book_info[0]}, Author: {book_info[1]}, Publisher: {book_info[4]}")
        else:
             print("No books avaible.")

    def add_book(self):
        title = input("Enter the book title: ")
        author = input("Enter the author: ")
        release_year = input("Enter the release year: ")
        num_pages = input("Enter the number of pages: ")
        publisher_name = input("Enter the publisher of the book: ")
        edition = input("Enter the edition of the book: ")

        book_info = f"{title},{author},{release_year},{num_pages},{publisher_name},{edition}\n"
        self.file.write(book_info)

    def remove_book(self):
        title = input("Enter the title of the book you want to remove: ")
        self.file.seek(0)
        books = self.file.readlines()
        new_books = [book for book in books if title not in book]
        self.file.seek(0)
        self.file.truncate(0)
        for book in new_books:
            self.file.write(book)

lib = Library()

while True:
    print("*** MENU ***")
    print("1) List Books")
    print("2) Add Book")
    print("3) Remove Book")
    print("4) Quit")

    choice = input("Enter your choice: ")

    if choice == '1':
        lib.list_books()
        print("All books listed successfully!")
    elif choice == '2':
        lib.add_book()
        print("Book added successfully!")
    elif choice == '3':
        lib.remove_book()
        print("Book removed successfully!")
    elif choice == '4':
        print("Have a nice day!")
        break
    else:
      print("Invalid choice. Please enter a number between 1 and 4.")